const UtilsLib = artifacts.require("./UtilsLib.sol");
const Owned = artifacts.require("./Owned.sol");
const Signable = artifacts.require("./Signable.sol");
const Trusteed = artifacts.require("./Trusteed.sol");
const Beneficiary = artifacts.require("./Beneficiary.sol");
const Sale = artifacts.require("./Sale.sol");
const Entity = artifacts.require("./Entity.sol");
const Trust = artifacts.require("./Trust.sol");
const LoanableTrust = artifacts.require("./LoanableTrust.sol");
const SalableTrust = artifacts.require("./SalableTrust.sol");
const TrustRE = artifacts.require("./TrustRE.sol");
const SmartTrustRE = artifacts.require("./SmartTrustRE.sol");
const EntityFactory = artifacts.require("./EntityFactory.sol");

module.exports = async (deployer) => {
  await deployer.deploy(UtilsLib);
  await deployer.link(UtilsLib, Sale);
  await deployer.link(UtilsLib, Beneficiary);
  await deployer.link(UtilsLib, Signable);
  await deployer.link(UtilsLib, LoanableTrust);
  await deployer.link(UtilsLib, SalableTrust);
  await deployer.link(UtilsLib, TrustRE);
  await deployer.link(UtilsLib, SmartTrustRE);
  await deployer.deploy(Trusteed);
  await deployer.deploy(Signable);
  await deployer.deploy(Owned);
  await deployer.deploy(Beneficiary);
  await deployer.deploy(Sale);
  await deployer.deploy(Entity);
  await deployer.deploy(Trust);
  await deployer.deploy(LoanableTrust);
  await deployer.deploy(SalableTrust);
  await deployer.deploy(TrustRE);
  await deployer.deploy(EntityFactory);
  await deployer.deploy(SmartTrustRE, EntityFactory.address);
};
